STATUS_APPLIED = 0
STATUS_GOT_UPDATE = 1

STATUS_LABELS = {
    STATUS_APPLIED: "Applied",
    STATUS_GOT_UPDATE: "Got update",
}

STATUS_COLORS = {
    STATUS_APPLIED: "#e03131",
    STATUS_GOT_UPDATE: "#2f9e44",
}
